import type { ExamBank } from '../../src/core/types';

/**
 * Sample bank 1 — original questions written for this app.
 *
 * Deliberately exercises every question type the engine supports, so the
 * renderers can be checked end to end without importing anything.
 */
export const NETWORKING_BANK: ExamBank = {
  id: 'sample-net-101',
  code: 'NET-101',
  title: 'Networking Fundamentals',
  vendor: 'Sample Content',
  description:
    'A short original practice bank covering addressing, protocols, routing and troubleshooting. Included to demonstrate every question type.',
  passingScore: 70,
  timeLimitMinutes: 30,
  questionCount: 15,
  version: '1.0',
  source: 'built-in',
  sections: [
    { id: 'addressing', title: 'Addressing & Subnetting', weight: 0.3 },
    { id: 'protocols', title: 'Protocols & Ports', weight: 0.3 },
    { id: 'routing', title: 'Routing & Switching', weight: 0.2 },
    { id: 'troubleshooting', title: 'Troubleshooting', weight: 0.2 },
  ],
  questions: [
    {
      id: 'net-101-q1',
      bankId: 'sample-net-101',
      sectionId: 'protocols',
      type: 'single',
      number: 1,
      stem: 'A web server must accept encrypted browser traffic. Which TCP port should be open on the firewall?',
      choices: [
        { id: 'A', text: '21' },
        { id: 'B', text: '80' },
        { id: 'C', text: '443' },
        { id: 'D', text: '3389' },
      ],
      correct: ['C'],
      explanation:
        'HTTPS uses TCP 443. Port 80 carries unencrypted HTTP, 21 is FTP control, and 3389 is RDP.',
      difficulty: 1,
      tags: ['ports', 'https'],
    },
    {
      id: 'net-101-q2',
      bankId: 'sample-net-101',
      sectionId: 'addressing',
      type: 'multiple',
      number: 2,
      stem: 'Which two of the following are RFC 1918 private address ranges? (Choose two.)',
      choices: [
        { id: 'A', text: '10.0.0.0/8' },
        { id: 'B', text: '172.32.0.0/12' },
        { id: 'C', text: '192.168.0.0/16' },
        { id: 'D', text: '169.254.0.0/16' },
      ],
      correct: ['A', 'C'],
      selectCount: 2,
      explanation:
        'RFC 1918 reserves 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16. 172.32.0.0/12 sits outside the reserved block, and 169.254.0.0/16 is APIPA link-local.',
      difficulty: 2,
      tags: ['rfc1918'],
    },
    {
      id: 'net-101-q3',
      bankId: 'sample-net-101',
      sectionId: 'addressing',
      type: 'single',
      number: 3,
      stem: 'A subnet must support at least 30 usable host addresses with the fewest addresses wasted. Which subnet mask should you use?',
      choices: [
        { id: 'A', text: '255.255.255.192' },
        { id: 'B', text: '255.255.255.224' },
        { id: 'C', text: '255.255.255.240' },
        { id: 'D', text: '255.255.255.248' },
      ],
      correct: ['B'],
      explanation:
        'A /27 (255.255.255.224) yields 32 addresses, 30 of them usable after the network and broadcast addresses. A /28 gives only 14 usable, and a /26 wastes 32 addresses.',
      reference: 'RFC 4632 — Classless Inter-domain Routing',
      difficulty: 2,
    },
    {
      id: 'net-101-q4',
      bankId: 'sample-net-101',
      sectionId: 'protocols',
      type: 'truefalse',
      number: 4,
      stem: 'UDP guarantees that datagrams arrive in the order they were sent.',
      choices: [
        { id: 'A', text: 'True' },
        { id: 'B', text: 'False' },
      ],
      correct: ['B'],
      explanation:
        'UDP is connectionless and offers no ordering, retransmission or delivery guarantee. Applications that need ordering implement it themselves or use TCP.',
      difficulty: 1,
    },
    {
      id: 'net-101-q5',
      bankId: 'sample-net-101',
      sectionId: 'troubleshooting',
      type: 'fill',
      number: 5,
      stem: 'Which command-line utility displays the path a packet takes to a destination host, listing each router hop along the way?\n\nType the Windows command name.',
      correct: ['tracert', 'tracert.exe'],
      explanation:
        'On Windows the utility is `tracert`; the Linux and macOS equivalent is `traceroute`.',
      difficulty: 1,
    },
    {
      id: 'net-101-q6',
      bankId: 'sample-net-101',
      sectionId: 'troubleshooting',
      type: 'ordering',
      number: 6,
      stem: 'Put the phases of the standard network troubleshooting methodology into the correct order.',
      choices: [
        { id: 'A', text: 'Identify the problem' },
        { id: 'B', text: 'Establish a theory of probable cause' },
        { id: 'C', text: 'Test the theory to determine the cause' },
        { id: 'D', text: 'Establish a plan of action and implement the solution' },
        { id: 'E', text: 'Verify full system functionality' },
        { id: 'F', text: 'Document findings, actions and outcomes' },
      ],
      correct: ['A', 'B', 'C', 'D', 'E', 'F'],
      explanation:
        'Gather information before theorising, prove the theory before acting, then verify and document. Documentation is always the final step.',
      difficulty: 2,
    },
    {
      id: 'net-101-q7',
      bankId: 'sample-net-101',
      sectionId: 'protocols',
      type: 'dragdrop',
      number: 7,
      stem: 'Match each protocol to the default port it listens on.',
      choices: [
        { id: 'A', text: '22' },
        { id: 'B', text: '25' },
        { id: 'C', text: '53' },
        { id: 'D', text: '67' },
      ],
      targets: [
        { id: 't-ssh', label: 'SSH' },
        { id: 't-smtp', label: 'SMTP' },
        { id: 't-dns', label: 'DNS' },
        { id: 't-dhcp', label: 'DHCP server' },
      ],
      correct: ['t-ssh=A', 't-smtp=B', 't-dns=C', 't-dhcp=D'],
      explanation:
        'SSH listens on 22, SMTP on 25, DNS on 53, and the DHCP server on UDP 67 (clients receive on 68).',
      difficulty: 2,
    },
    {
      id: 'net-101-q8',
      bankId: 'sample-net-101',
      sectionId: 'routing',
      type: 'hotspot',
      number: 8,
      stem: 'A switch port must carry traffic for several VLANs to another switch, and a second port connects a single desktop PC.\n\nChoose the correct configuration for each port.',
      hotspots: [
        {
          id: 'h-uplink',
          label: 'Port connecting the two switches',
          options: ['Access port', 'Trunk port', 'Routed port'],
          correct: 'Trunk port',
        },
        {
          id: 'h-desktop',
          label: 'Port connecting the desktop PC',
          options: ['Access port', 'Trunk port', 'Routed port'],
          correct: 'Access port',
        },
      ],
      correct: ['h-uplink=Trunk port', 'h-desktop=Access port'],
      explanation:
        'Inter-switch links carrying multiple VLANs are trunk ports and tag frames (802.1Q). An end device belongs to a single VLAN and connects to an untagged access port.',
      difficulty: 2,
    },
    {
      id: 'net-101-q9',
      bankId: 'sample-net-101',
      sectionId: 'routing',
      type: 'single',
      number: 9,
      stem: 'A router has these routes to 10.1.5.0/24 in its table:\n\n```\nO    10.1.0.0/16   [110/20]\nS    10.1.5.0/24   [1/0]\nR    10.1.5.0/24   [120/3]\n```\n\nWhich route does the router install for traffic to 10.1.5.10?',
      choices: [
        { id: 'A', text: 'The OSPF route, because it has the lowest metric' },
        { id: 'B', text: 'The static route, because it has the lowest administrative distance' },
        { id: 'C', text: 'The RIP route, because RIP updates most frequently' },
        { id: 'D', text: 'All three, load-balanced equally' },
      ],
      correct: ['B'],
      explanation:
        'The longest prefix match narrows it to the two /24 routes, then administrative distance decides: static (1) beats RIP (120). Metrics are only compared within the same protocol.',
      difficulty: 3,
      tags: ['routing-table', 'administrative-distance'],
    },
    {
      id: 'net-101-q10',
      bankId: 'sample-net-101',
      sectionId: 'troubleshooting',
      type: 'single',
      number: 10,
      stem: 'A workstation reports the address 169.254.18.44 and cannot reach any internal server. What is the most likely cause?',
      choices: [
        { id: 'A', text: 'The DNS server is unreachable' },
        { id: 'B', text: 'The workstation could not reach a DHCP server' },
        { id: 'C', text: 'The default gateway is misconfigured' },
        { id: 'D', text: 'The subnet mask is too small' },
      ],
      correct: ['B'],
      explanation:
        'The 169.254.0.0/16 range is APIPA. A host self-assigns from it only after failing to obtain a DHCP lease.',
      difficulty: 1,
    },
    {
      id: 'net-101-q11',
      bankId: 'sample-net-101',
      sectionId: 'protocols',
      type: 'multiple',
      number: 11,
      stem: 'Which two protocols operate at the transport layer of the OSI model? (Choose two.)',
      choices: [
        { id: 'A', text: 'TCP' },
        { id: 'B', text: 'IP' },
        { id: 'C', text: 'UDP' },
        { id: 'D', text: 'ARP' },
      ],
      correct: ['A', 'C'],
      selectCount: 2,
      explanation:
        'TCP and UDP are layer 4. IP is layer 3, and ARP bridges layers 2 and 3 by resolving IP addresses to MAC addresses.',
      difficulty: 1,
    },
    {
      id: 'net-101-q12',
      bankId: 'sample-net-101',
      sectionId: 'addressing',
      type: 'single',
      number: 12,
      stem: 'How many usable host addresses does the subnet 192.168.10.0/26 provide?',
      choices: [
        { id: 'A', text: '30' },
        { id: 'B', text: '62' },
        { id: 'C', text: '64' },
        { id: 'D', text: '126' },
      ],
      correct: ['B'],
      explanation:
        'A /26 has 6 host bits: 2^6 = 64 addresses, minus the network and broadcast addresses leaves 62 usable.',
      difficulty: 2,
    },
    {
      id: 'net-101-q13',
      bankId: 'sample-net-101',
      sectionId: 'routing',
      type: 'matching',
      number: 13,
      stem: 'Match each device to the OSI layer it primarily operates at.',
      choices: [
        { id: 'A', text: 'Layer 1 — Physical' },
        { id: 'B', text: 'Layer 2 — Data link' },
        { id: 'C', text: 'Layer 3 — Network' },
      ],
      targets: [
        { id: 't-hub', label: 'Hub' },
        { id: 't-switch', label: 'Unmanaged switch' },
        { id: 't-router', label: 'Router' },
      ],
      correct: ['t-hub=A', 't-switch=B', 't-router=C'],
      explanation:
        'A hub repeats electrical signals (layer 1), a switch forwards frames by MAC address (layer 2), and a router forwards packets by IP address (layer 3).',
      difficulty: 1,
    },
    {
      id: 'net-101-q14',
      bankId: 'sample-net-101',
      sectionId: 'troubleshooting',
      type: 'single',
      number: 14,
      stem: 'Users can reach internal servers by IP address but not by hostname. Which service should you check first?',
      choices: [
        { id: 'A', text: 'DHCP' },
        { id: 'B', text: 'DNS' },
        { id: 'C', text: 'NTP' },
        { id: 'D', text: 'SNMP' },
      ],
      correct: ['B'],
      explanation:
        'Connectivity by IP proves routing works, so the failure is in name resolution — DNS.',
      difficulty: 1,
    },
    {
      id: 'net-101-q15',
      bankId: 'sample-net-101',
      sectionId: 'addressing',
      type: 'fill',
      number: 15,
      stem: 'What is the network address of the host 172.16.35.77/20?\n\nEnter the address only, for example 10.0.0.0.',
      correct: ['172.16.32.0'],
      explanation:
        'A /20 gives a block size of 16 in the third octet: 0, 16, 32, 48… The host 172.16.35.77 falls in the block starting at 172.16.32.0.',
      difficulty: 3,
    },
  ],
};
